const { Property } = require("../models");

const propertydata = [
  {
    id: 1,
    streetNumber: "123",
    streetName: "Parkdale Road",
    unitNumber: "33",
    postalCode: "XXX YYY",
    city: "Toronto",
    price: "$850,000",
    bedrooms: "3",
    bathrooms: "2",
    listingType: "For Sale",
    ownerID: 1,
  },
  {
    id: 2,
    streetNumber: "456",
    streetName: "Streetsdale Avenue",
    postalCode: "XXX YYY",
    city: "Toronto",
    price: "$950,000",
    bedrooms: "4",
    bathrooms: "1",
    listingType: "For Sale",
    ownerID: 2,
  },
  {
    id: 3,
    streetNumber: "689",
    streetName: "Clifden Road",
    unitNumber: "42",
    postalCode: "XXX YYY",
    city: "Toronto",
    price: "$700,000",
    bedrooms: "1",
    bathrooms: "1",
    listingType: "For Sale",
    ownerID: 3,
  },
  {
    id: 4,
    streetNumber: "135",
    streetName: "Lakeshore Road",
    postalCode: "XXX YYY",
    city: "Toronto",
    price: "$2,500",
    bedrooms: "1",
    bathrooms: "1",
    listingType: "For Rent",
    ownerID: 3,
  },
  {
    id: 5,
    streetNumber: "123",
    streetName: "Bloor Street",
    unitNumber: "2",
    postalCode: "XXX YYY",
    city: "Toronto",
    price: "$3,800",
    bedrooms: "3",
    bathrooms: "2",
    listingType: "For Rent",
    ownerID: 1,
  },
  {
    id: 6,
    streetNumber: "123",
    streetName: "Parkdale Road",
    unitNumber: "33",
    postalCode: "XXX YYY",
    city: "Toronto",
    price: "$3,000",
    bedrooms: "2",
    bathrooms: "1",
    listingType: "For Rent",
    ownerID: 2,
  },
];

const seedPost = () => Property.bulkCreate(propertydata);

module.exports = seedPost;
